# user should change the log, output, and error locations

log    = /scratch/brianclark/demo/demo.$(Process).log
output = /scratch/brianclark/demo/demo.$(Process).out
error  = /scratch/brianclark/demo/demo.$(Process).err

universe = vanilla
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
getenv = true
request_memory = 2GB

executable = job.sh
arguments = $(Process)

# queue two copies
# to queue more copies (e.g. 100) change 2 to 100
queue 2